---
  - name: Create file for auth pacemaker
    copy:
      dest: "/tmp/pacemakerauth.expect"
      content: |
        #!/usr/bin/expect -f
        set timeout -1
        spawn pcs cluster auth msk-pcs-1 msk-pcs-2 msk-pcs-3
        expect "Username:"
        send -- "hacluster\r"
        expect "Password:"
        send -- "{{ newpassword }}\r"
        expect eof
      mode: 0775
      owner: root
    when: ansible_hostname == 'msk-pcs-1'

  - name: Configure Pacemaker Cluster
    shell: |
        /tmp/pacemakerauth.expect
        pcs cluster setup --name pcs_cluster msk-pcs-1 msk-pcs-2 msk-pcs-3
        pcs cluster start --all
        pcs cluster enable --all
        pcs property set stonith-enabled=false
        pcs property set no-quorum-policy=ignore
        pcs resource create dlm systemd:dlm op monitor interval=10s on-fail=ignore clone interleave=true ordered=true
        pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=10s on-fail=ignore clone interleave=true ordered=true
        pcs constraint order start dlm-clone then clvmd-clone
        sleep 30
        pvcreate /dev/mapper/yellow-msk-iscsi-1
        sleep 10
        vgcreate -Ay -cy cluster_vg /dev/mapper/yellow-msk-iscsi-1
        sleep 5
        lvcreate -l 100%FREE -n cluster_lv cluster_vg
        sleep 5
        echo 'y' | mkfs.gfs2 -j3 -p lock_dlm -t pcs_cluster:gfs2 /dev/cluster_vg/cluster_lv
        sleep 5
        pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=ignore clone interleave=true
        sleep 5
        pcs constraint order start clvmd-clone then clusterfs-clone
        pcs constraint colocation add clusterfs-clone with clvmd-clone
    when: ansible_hostname == 'msk-pcs-1'